### ISSUE TITLE
输入中文就会报错

### ISSUE THREAD

**Issue by luxinxin1995** [wclimb/Koa2-blog#38]
你好，为什么我运行之后，只要输入中文就会报错啊，自己也尝试百度把数据库编码方式改为utf8，这样还是不行

Error: ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
      at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
      at Query.ErrorPacket (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
      at Protocol._parsePacket (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Protocol.js:278:23)
      at Parser.write (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Parser.js:76:12)
      at Protocol.write (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:91:28)
      at Socket.<anonymous> (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:502:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
      --------------------
      at Protocol._enqueue (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Protocol.js:144:48)
      at PoolConnection.query (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:200:25)
      at pool.getConnection (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\lib\mysql.js:19:20)
      at Ping.onOperationComplete (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Pool.js:110:5)
      at Ping.<anonymous> (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:502:10)
      at Ping._callback (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:468:16)
      at Ping.Sequence.end (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
      at Ping.Sequence.OkPacket (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)
      at Protocol._parsePacket (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Protocol.js:278:23)
      at Parser.write (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Parser.js:76:12)
      at Protocol.write (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\protocol\Protocol.js:38:16)
      at Socket.<anonymous> (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:91:28)
      at Socket.<anonymous> (C:\Users\Administrator\Desktop\文件dsd\Koa2-blog-master\node_modules\mysql\lib\Connection.js:502:10)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)

**Comment by wunci** [comment]
https://stackoverflow.com/questions/1008287/illegal-mix-of-collations-mysql-error
